[tool.pytest.ini_options]
pythonpath = [
    "."
]

[tool.black]
line-length = 79
assert_used:
  skips: ['*_test.py', '*test_*.py']
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''