"""Initial migration

Revision ID: 73c5861f8f69
Revises:
Create Date: 2022-12-12 13:50:56.024189

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "73c5861f8f69"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cliente",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nome", sa.String(length=50), nullable=False),
        sa.Column("email", sa.String(length=50), nullable=False),
        sa.Column("telefone", sa.String(length=11), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "servico",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("preco", sa.Numeric(precision=8, scale=2), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "pet",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("especie", sa.String(length=50), nullable=False),
        sa.Column("raca", sa.String(length=50), nullable=False),
        sa.Column("cliente_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["cliente_id"],
            ["cliente.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("pet")
    op.drop_table("servico")
    op.drop_table("cliente")
    # ### end Alembic commands ###
