"""Corrige coluna nome da tabela Pets

Revision ID: 82cb83e4be04
Revises: 73c5861f8f69
Create Date: 2022-12-12 14:32:33.286929

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "82cb83e4be04"
down_revision = "73c5861f8f69"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("pet", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("nome", sa.String(length=50), nullable=False)
        )
        batch_op.drop_column("name")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("pet", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("name", mysql.VARCHAR(length=50), nullable=False)
        )
        batch_op.drop_column("nome")

    # ### end Alembic commands ###
